import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { createProject, deleteProject, getProjects } from "@/lib/api/service";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export async function getServerSideProps() {
  const projects = await getProjects();
  return {
    props: {
      projects,
    },
  };
}

export default function Home({ projects }: { projects: any[] }) {
  console.log(projects);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <button
            onClick={async () => {
              const newProject = {
                title: "New Project",
                description: "This is a new project",
                tech: "tech 1",
                image: "image 1",
              };
              const createdProject = await createProject(newProject);
              console.log("Created Project:", createdProject);
            }}
          >
            Create New Project
          </button>
          {projects.map((project) => (
            <div key={project.id}>
              <h2>{project.title}</h2>
              <button
                onClick={async () => {
                  await deleteProject(project.id);
                }}
              >
                Delete
              </button>
            </div>
          ))}
        </main>
      </div>
    </>
  );
}
