import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { getProjects } from "@/lib/api/service";
import ProjectCard from "@/components/atoms/projectCard";

export async function getServerSideProps() {
  const projects = await getProjects();
  return {
    props: {
      projects,
    },
  };
}

export default function Home({ projects }: { projects: any[] }) {
  console.log(projects);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${styles.page}`}>
        <main className={styles.main}>
          <h1 className={styles.title}>My Projects</h1>
          <div className={styles.grid}>
            {projects.map((project) => (
              <ProjectCard key={project.id} project={project} />
            ))}
          </div>
        </main>
      </div>
    </>
  );
}
